[package]
name = "voxel_visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.16"
winit = "0.28"
pollster = "0.3"
glam = "0.26"
rand = "0.8"
env_logger = "0.11.6"
bytemuck = { version = "1.14.0", features = ["derive"] }
noise = "0.9.0"
